//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku
{
    using System;
    using System.Collections.Generic;
    
    public partial class Save
    {
        public int Id { get; set; }
        public string MatrixData { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string GameType { get; set; }
    }
}
